baseURL = "https://www.giorgosneokleous.com"
languageCode = "en-us"
title = "Giorgos Neokleous"
theme = "anubis"
paginate = 5

disqusShortname = "www-giorgosneokleous-com"
googleAnalytics = "UA-84803609-1"
enableRobotsTXT = true

publishDir = "docs"

[author]
  name = "Giorgos Neokleous"

[params]
   author = "Giorgos Neokleous"
   description = "Giorgos Neokleous's stories about Android Development and Programming!"
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "dark"
   readMore = false
   env = "production"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/neokleoys2005"
    weight = 3
  
  [[menu.main]]
    identifier = "linkedin"
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://www.linkedin.com/in/giorgos-neokleous/"
    weight = 4  

  [[menu.main]]
    identifier = "github"
    pre = "<i class='fa fa-github-square'></i>"
    url = "https://github.com/giorgosneokleous93/"
    weight = 5

  [[menu.main]]
    identifier = "stackoverflow"
    pre = "<i class='fa fa-stack-overflow'></i>"
    url = "https://stackoverflow.com/users/3330058/giorgos-neokleous"
    weight = 6

  [[menu.footer]]
    name = "Privacy Policy"
    identifier = "privacy-policy"
    pre = "<i class='fa fa-cookie-bite'></i>"
    url = "/privacy-policy/"
    weight = 1

  [[menu.footer]]
    name = "Terms and Conditions"
    identifier = "terms-and-conditions"
    pre = "<i class='fa fa-book-open'></i>"
    url = "/terms-and-conditions/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
