baseURL = "https://www.giorgosneokleous.com"
languageCode = "en-us"
title = "Giorgos Neokleous"
theme = "anubis"
paginate = 5

disqusShortname = "www-giorgosneokleous-com"
googleAnalytics = "UA-84803609-1"
enableRobotsTXT = true

publishDir = "docs"

[author]
  name = "Giorgos Neokleous"

[params]
   author = "Giorgos Neokleous"
   description = "Giorgos Neokleous's stories about Android Development and Programming!"
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "dark"
   readMore = false
   env = "production"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    identifier = "Blog"
    url = "/posts/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true